blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/[owner]/[repo]/wiki
    about: Check our documentation for answers
  - name: Security Issue
    url: https://github.com/[owner]/[repo]/security/advisories
    about: Report a security vulnerability privately
